### ISSUE TITLE
Update to new versions

### ISSUE THREAD

**Issue by abebeos** [SecureSECO/SearchSECOController#82]
(re #79)

#79 has been identified as a "threading bug, possibly racing", which occurs only on Ubuntu.

There is a slight chance that the bug will be eliminated by updating to newer versions of the libraries used (starting with the threading library).

Take into account that this can introduce other side-effects and regressions.

## Tasks

- [x] build with clang10 => still bugs
- [x] build with g++-10 => still bugs
- [x] build with g++-11 => still bugs
- => its not the compiler 
- [x] current boost 1,71, trying boost 1.79 => still bugs
- [x] update the threading library => not feasible, std-library is used
- [x] update anything related => nothing more found
  - [x] update to umbuntu 22.04 aborted, high effort, to many follow-up tasks for now

## Follow-up

- [ ] #83
  - [ ] #84 

## Final Fallback (avoid this)

- Full update (ubuntu 20.04 => 22.04, srcML latest, ANTLR runtime, etc. )

**Comment by abebeos** [comment]
closing, further work within the follow-ups #83, #84
